export const moduleCategories = {
  all: { zh: "全部", en: "All" },
  modelFitting: { zh: "模型拟合", en: "Model fitting" },
  errorDiagnostics: { zh: "误差诊断", en: "Error diagnostics" },
  statisticalInference: { zh: "统计推断", en: "Statistical inference" },
  methodDevelopment: { zh: "方法开发", en: "Method development" },
  methodValidation: { zh: "方法验证", en: "Method validation" },
  dataProcessing: { zh: "数据处理", en: "Data processing" },
  general: { zh: "通用", en: "General" },
};

export const modules = [
  {
    id: "anova-explorer",
    type: "explore",
    route: "/learn/anova-explorer/",
    status: "ready",
    featured: true,
    homeOrder: 1,
    listOrder: 1,
    category: "modelFitting",
    title: { zh: "探索方差分析", en: "Explore ANOVA" },
    homeTitle: { zh: "探索方差分析", en: "Explore ANOVA" },
    homeTitleLines: { zh: ["探索", "方差分析"], en: ["Explore", "ANOVA"] },
    homeNote: { zh: "交互式方差分析可视化。", en: "Interactive ANOVA visualization." },
    description: {
      zh: "理解模型如何分解数据中的变异。",
      en: "See how a model separates variation in data.",
    },
    luckyEligible: true,
    keywords: ["ANOVA", "variance", "方差", "变异", "模型"],
    tags: ["model", "statistics"],
  },
  {
    id: "ci-explorer",
    type: "explore",
    route: "/learn/ci-explorer/",
    status: "ready",
    featured: true,
    homeOrder: 2,
    listOrder: 2,
    category: "statisticalInference",
    title: { zh: "探索置信区间", en: "Explore Confidence Interval" },
    homeTitle: { zh: "探索置信区间", en: "Explore CI" },
    homeTitleLines: { zh: ["探索", "置信区间"], en: ["Explore", "CI"] },
    homeNote: {
      zh: "交互式置信区间可视化。",
      en: "Interactive confidence interval visualization.",
    },
    description: {
      zh: "理解估计值及其不确定性。",
      en: "Understand estimates and their uncertainty.",
    },
    luckyEligible: true,
    keywords: ["confidence interval", "CI", "置信区间", "uncertainty", "不确定性"],
    tags: ["inference", "statistics"],
  },
  {
    id: "residual-explorer",
    type: "explore",
    route: "/learn/residual-explorer/",
    status: "ready",
    featured: true,
    homeOrder: 3,
    listOrder: 3,
    category: "errorDiagnostics",
    title: { zh: "探索残差分布", en: "Explore Residual Distribution" },
    homeTitle: { zh: "探索残差分布", en: "Explore residuals" },
    homeTitleLines: { zh: ["探索", "残差分布"], en: ["Explore", "residuals"] },
    homeNote: { zh: "探索拟合后的残差结构。", en: "Explore residual structure after fitting." },
    description: {
      zh: "通过残差诊断模型假设。",
      en: "Use residuals to diagnose model assumptions.",
    },
    luckyEligible: true,
    keywords: ["residual", "残差", "distribution", "分布", "diagnostics"],
    tags: ["diagnostics", "model"],
  },
  {
    id: "validation-explorer",
    type: "explore",
    status: "planned",
    featured: true,
    homeOrder: 4,
    listOrder: 4,
    category: "statisticalInference",
    title: { zh: "探索方法验证", en: "Explore Method Validation" },
    homeTitle: { zh: "探索方法验证", en: "Explore validation" },
    homeTitleLines: { zh: ["探索", "方法验证"], en: ["Explore", "validation"] },
    homeNote: { zh: "方法验证学习模块。", en: "Method validation learning." },
    description: {
      zh: "理解方法验证中的证据与判断。",
      en: "Explore evidence and decisions in method validation.",
    },
    keywords: ["validation", "方法验证", "method"],
    tags: ["validation", "inference"],
  },
  {
    id: "specification-limit-calculator",
    type: "tools",
    route: "/tools/specification-limit-calculator/",
    status: "ready",
    featured: true,
    homeOrder: 1,
    listOrder: 1,
    category: "methodDevelopment",
    title: { zh: "质量标准限度计算器", en: "Specification Limit Calculator" },
    homeTitle: { zh: "质量标准限度计算器", en: "Specification Limit Calculator" },
    homeTitleLines: { zh: ["质量标准限度", "计算器"], en: ["Specification", "Limit Calculator"] },
    homeNote: { zh: "质量标准限度工作流。", en: "Specification limit workflow." },
    description: {
      zh: "建立质量标准限度的计算工作流。",
      en: "Build a specification-limit calculation workflow.",
    },
    luckyEligible: true,
    keywords: ["specification", "limit", "质量标准", "限度"],
    tags: ["development", "specification"],
  },
  {
    id: "unit-converter",
    type: "tools",
    route: "/tools/converter/",
    status: "ready",
    featured: true,
    homeOrder: 2,
    listOrder: 2,
    category: "dataProcessing",
    title: { zh: "浓度单位转换器", en: "Unit Converter" },
    homeTitle: { zh: "浓度单位转换器", en: "Unit Converter" },
    homeTitleLines: { zh: ["浓度单位", "转换器"], en: ["Unit", "Converter"] },
    homeNote: { zh: "科学浓度换算。", en: "Scientific concentration conversion." },
    description: { zh: "进行科学浓度单位换算。", en: "Convert scientific concentration units." },
    luckyEligible: true,
    keywords: ["unit", "converter", "concentration", "单位", "浓度", "换算"],
    tags: ["conversion", "data"],
  },
  {
    id: "validation-sample-size",
    type: "tools",
    status: "planned",
    featured: true,
    homeOrder: 3,
    listOrder: 3,
    category: "methodValidation",
    title: { zh: "验证样本量计算器", en: "Validation Sample Size Calculator" },
    homeTitle: { zh: "验证样本量计算器", en: "Validation Sample Size" },
    homeTitleLines: { zh: ["验证样本量", "计算器"], en: ["Validation Sample", "Size Calculator"] },
    description: {
      zh: "根据接受标准评估验证样本量。",
      en: "Estimate validation sample size from acceptance criteria.",
    },
    keywords: ["sample size", "validation", "样本量", "方法验证"],
    tags: ["validation", "statistics"],
  },
  {
    id: "oos-risk-explorer",
    type: "tools",
    status: "planned",
    featured: true,
    homeOrder: 4,
    listOrder: 4,
    category: "methodValidation",
    title: { zh: "OOS 风险探索器", en: "OOS Risk Explorer" },
    homeTitle: { zh: "OOS 风险探索器", en: "OOS Risk Explorer" },
    homeTitleLines: { zh: ["OOS 风险", "探索器"], en: ["OOS Risk", "Explorer"] },
    description: {
      zh: "用于评估偏差、精密度与超标风险。",
      en: "A forthcoming workspace for bias, precision, and out-of-specification risk.",
    },
    keywords: ["OOS", "risk", "超标", "风险", "precision", "偏差"],
    tags: ["validation", "risk"],
  },
  {
    id: "validation-simulator",
    type: "tools",
    status: "planned",
    featured: false,
    listOrder: 5,
    category: "methodDevelopment",
    title: { zh: "方法验证模拟器", en: "Method Validation Simulator" },
    homeTitle: { zh: "方法验证模拟器", en: "Validation Simulator" },
    description: {
      zh: "模拟验证设计、证据矩阵与结果风险。",
      en: "Simulate validation design, evidence, and reportable-result risk.",
    },
    keywords: ["simulator", "validation", "模拟", "方法验证"],
    tags: ["development", "validation"],
  },
  {
    id: "validation-calculator",
    type: "tools",
    status: "planned",
    featured: false,
    listOrder: 6,
    category: "methodValidation",
    title: { zh: "方法验证计算器", en: "Validation Calculator" },
    homeTitle: { zh: "方法验证计算器", en: "Validation Calculator" },
    homeNote: { zh: "方法验证实用工具。", en: "Validation utilities." },
    description: {
      zh: "汇集方法验证中的常用计算。",
      en: "A forthcoming collection of method-validation calculations.",
    },
    keywords: ["validation", "calculator", "方法验证", "计算器"],
    tags: ["validation"],
  },
];

export const getModules = (type) => modules.filter((module) => module.type === type);
export const getFeaturedModules = (type) =>
  getModules(type)
    .filter((module) => module.featured)
    .sort((a, b) => a.homeOrder - b.homeOrder)
    .slice(0, 4);
